name: Hello QA
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello QA
        run: echo "Hello QA!"

      - name: Check Node.js version
        run: node --version

    steps:
      - name: Bye QA
        run: echo "Adios QA!"
        
      - name: sayBye
        run: echo "Goodbye QA!"